// ─── Brand Constants ───
export const BRAND = {
  name: "Tantalizing Tallow",
  tagline: "Skincare should be simple, sensual, and wildly effective — just like nature intended.",
  freeShipMin: 75,
  colors: {
    bg: "#0a0a0a",
    surface: "#141414",
    card: "#1a1a1a",
    gold: "#c9a84c",
    goldLight: "#e2c97e",
    goldDark: "#a68935",
    text: "#f5f0e8",
    textMuted: "#a09880",
    accent: "#2a2418",
    border: "#2a2520",
  },
};

// ─── Product Database ───
// These are populated from your Shopify store via the Storefront API.
// The static data below serves as the fallback / offline mode so the
// site always renders even without an API connection.
export const PRODUCTS = [
  {
    id: 1, name: "Blue Tansy", handle: "blue-tansy-whipped-face-cream",
    price: 20, priceFrom: true,
    category: "face", skinType: ["sensitive", "dry", "combination", "mature"],
    shortDesc: "Calming whipped face cream for sensitive and dry skin",
    description: "A calming, whipped face cream designed to soothe sensitive skin, reduce the appearance of redness, and deeply nourish while maintaining a soft, lightweight feel.",
    ingredients: ["Grass-fed tallow", "Blue tansy", "Manuka honey", "Castor oil", "Frankincense", "Ylang ylang"],
    benefits: ["Calms redness and irritation", "Supports skin barrier", "Lightweight moisture without heaviness", "Leaves skin soft and balanced"],
    rating: 4.9, reviews: 47,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_e92dfc5c-6957-496d-bc61-457818162326.png",
    badge: "Bestseller",
  },
  {
    id: 2, name: "Clarifying Face Cream", handle: "acne-face-cream",
    price: 20,
    category: "face", skinType: ["acne-prone", "oily", "combination", "sensitive"],
    shortDesc: "Clear & Calm tallow face cream for blemish-prone skin",
    description: "A deeply nourishing, lightweight face cream designed to calm blemish-prone skin while restoring balance and hydration — without clogging pores or causing irritation.",
    ingredients: ["Grass-fed tallow", "Manuka honey 829+", "Black seed oil", "Tea tree oil", "Helichrysum"],
    benefits: ["Calms breakouts and redness", "Supports balanced less oily skin", "Lightweight non-greasy hydration", "Promotes clearer smoother complexion"],
    rating: 4.8, reviews: 32,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_b69b58da-634f-42a6-9315-a3074867cc93.jpg",
  },
  {
    id: 3, name: "Cleansing Balm", handle: "whipped-tallow-cleansing-balm",
    price: 12,
    category: "cleanser", skinType: ["dry", "mature", "sensitive", "combination"],
    shortDesc: "Luxurious whipped cleansing balm that melts away makeup",
    description: "A luxurious, whipped cleansing balm that gently melts away makeup, sunscreen, and impurities while leaving skin soft, nourished, and balanced. Designed for mature and sensitive skin without stripping moisture.",
    ingredients: ["Grass-fed tallow", "Rosehip oil", "Castor oil", "Frankincense", "Lavender"],
    benefits: ["Removes makeup without stripping", "Leaves skin hydrated and soft", "Supports radiant-looking skin", "Calms delicate or reactive skin"],
    rating: 4.7, reviews: 28,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_3a7c3046-cb14-42cc-9a23-f7390a50d103.png",
  },
  {
    id: 4, name: "Vanilla Tallow Body Butter", handle: "cost-effective-vanilla-tallow-body-butter-face-cream",
    price: 6, priceFrom: true,
    category: "body", skinType: ["dry", "sensitive", "combination", "mature"],
    shortDesc: "Minimalist vanilla tallow moisturizer for pure hydration",
    description: "A minimalist, deeply nourishing moisturizer made for pure hydration and skin barrier support. Rich, balm-like texture melts into skin with body heat. Ideal for those who want simple, effective skincare.",
    ingredients: ["Grass-fed tallow", "Vanilla infusion"],
    benefits: ["Deeply moisturizes and protects skin barrier", "Reduces dryness and flakiness", "Long-lasting hydration", "Simple formula for sensitive skin"],
    rating: 4.9, reviews: 89,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_8552804f-9d37-49aa-bbaa-309c203b10d5.png",
    badge: "Best Value",
  },
  {
    id: 5, name: "Custom Whipped Body Butter", handle: "vanilla-velvet-body-butter",
    price: 20,
    category: "body", skinType: ["all"],
    shortDesc: "Pure, essential oil, or fragrance options",
    description: "Your tallow, your way. Choose pure unscented, essential oil blends, or fragrance options. Each jar is hand-whipped to a cloud-like consistency from triple-filtered grass-fed tallow.",
    ingredients: ["Grass-fed tallow", "Your choice of scent", "Jojoba oil"],
    benefits: ["Customizable scent", "Hand-whipped texture", "Ultra-moisturizing", "Clean ingredients"],
    rating: 4.8, reviews: 56,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_cece441f-aec1-4fdd-bf1e-5a2f3ac7b3af.png",
  },
  {
    id: 6, name: "Frankincense & Manuka Honey Face Cream", handle: "frankincense-manuka-honey-face-cream",
    price: 40,
    category: "face", skinType: ["dry", "sensitive", "mature", "combination"],
    shortDesc: "Premium face cream with high-potency Manuka honey 1122+",
    description: "A luxurious whipped face cream that deeply hydrates and nourishes while supporting a smooth, resilient, and radiant complexion. Enhanced with high-potency Manuka honey 1122+ for elevated soothing and skin-recovery support.",
    ingredients: ["Grass-fed tallow", "Manuka honey 1122+", "Castor oil", "Frankincense"],
    benefits: ["Intensely hydrates dry skin", "Supports skin repair and recovery", "Improves fine lines and texture", "Calms sensitive or reactive skin"],
    rating: 5.0, reviews: 23,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_29113693-29da-4026-8e80-da9c0f5f5ea3.png",
    badge: "Premium",
  },
  {
    id: 7, name: "Frankincense & Vanilla Face Cream", handle: "vanilla-frankincense-face-cream",
    price: 22,
    category: "face", skinType: ["dry", "sensitive", "mature", "combination"],
    shortDesc: "Luxurious whipped face cream with Manuka honey 829+",
    description: "A luxurious whipped face cream that deeply hydrates and nourishes the skin while supporting a soft, smooth, and radiant complexion. Formulated with high-grade Manuka honey 829+ for enhanced soothing and skin-support benefits.",
    ingredients: ["Grass-fed tallow", "Manuka honey 829+", "Castor oil", "Frankincense", "Vanilla infusion"],
    benefits: ["Deeply hydrates depleted skin", "Improves fine lines and texture", "Supports healthier skin barrier", "Leaves skin smooth and radiant"],
    rating: 4.8, reviews: 41,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_e3c864e2-f288-4ab6-b18f-fe62e38199e0.png",
  },
  {
    id: 8, name: "Frosted Mint Shimmer Body Butter", handle: "summer-shimmer-body-butter",
    price: 16,
    category: "body", skinType: ["all"],
    shortDesc: "Whipped tallow body butter with shimmer",
    description: "A playful twist on our classic body butter. Cooling mint meets a subtle shimmer for skin that glows. Perfect for summer evenings or anytime you want that extra radiance.",
    ingredients: ["Grass-fed tallow", "Peppermint oil", "Mica shimmer", "Coconut oil"],
    benefits: ["Cooling sensation", "Subtle shimmer glow", "Deep moisture", "Fun & playful"],
    rating: 4.7, reviews: 19,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_1a58a8db-7e15-4eea-84c1-c8752e5a0e0a.png",
  },
  {
    id: 9, name: "Hair & Scalp Oil", handle: "nourish-restore-hair-oil",
    price: 18,
    category: "hair", skinType: ["dry", "mature", "combination", "sensitive"],
    shortDesc: "Lightweight hair oil for thicker, shinier hair",
    description: "A lightweight, nutrient-rich hair oil designed to deeply nourish the scalp, enhance shine, and support the appearance of fuller, healthier-looking hair. Ideal for restoring softness and vitality to dry or damaged strands.",
    ingredients: ["Grass-fed tallow", "Castor oil", "Argan oil", "Manuka honey", "Rosemary"],
    benefits: ["Improves appearance of thicker, fuller hair", "Hydrates dry scalp and brittle ends", "Enhances natural shine and smoothness", "Supports healthier scalp environment"],
    rating: 4.6, reviews: 34,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_77a7760d-54db-40a3-a878-2d94a2c60fbb.jpg?v=1747893332",
  },
  {
    id: 10, name: "Hyaluronic Acid Serum", handle: "hydrabloom-botanical-serum",
    price: 12,
    category: "serum", skinType: ["dry", "mature", "combination", "sensitive"],
    shortDesc: "Hydrating serum for all skin types",
    description: "A lightweight, hydrating facial serum designed to refresh and soften the appearance of skin while promoting a smooth, radiant glow. Layer under your tallow cream for maximum hydration.",
    ingredients: ["Hyaluronic acid", "Aloe vera", "Frankincense", "Helichrysum", "Lemon"],
    benefits: ["Deeply hydrates for plump, dewy look", "Softens appearance of fine lines", "Lightweight layering without heaviness", "Supports refreshed radiant complexion"],
    rating: 4.7, reviews: 22,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_1b821661-94b3-4183-be44-ff92af969fcd.png",
  },
  {
    id: 11, name: "Lavender & Vanilla Magnesium Sleep Balm", handle: "lavender-and-magnesium-calming-cream",
    price: 18, priceFrom: true,
    category: "body", skinType: ["dry", "sensitive", "mature", "combination"],
    shortDesc: "Calming body butter for relaxation and better sleep",
    description: "A deeply calming, ultra-nourishing body butter designed to relax the body, support restful sleep, and restore dry skin. Perfect for winding down and creating a soothing nighttime ritual.",
    ingredients: ["Magnesium", "Lavender", "Vanilla", "Grass-fed tallow"],
    benefits: ["Calms body and mind before sleep", "Relieves tension in sore muscles", "Deeply hydrates and softens dry skin", "Promotes restful evening routine"],
    rating: 4.9, reviews: 67,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_8ab265f4-f5ed-42aa-a91a-0b83eb1837a7.png",
    badge: "Fan Favorite",
  },
  {
    id: 12, name: "Luxe Face Cream", handle: "luxe-face-cream",
    price: 60,
    category: "face", skinType: ["dry", "mature", "combination", "sensitive"],
    shortDesc: "Ultra-premium tallow face cream with bakuchiol and rosehip",
    description: "A rich, whipped facial cream designed to deeply nourish and support smoother, more radiant-looking skin. Crafted for a luxurious feel, it helps improve the appearance of dryness, uneven tone, and visible signs of aging.",
    ingredients: ["Grass-fed tallow", "Manuka honey", "Bakuchiol", "Rosehip oil", "Tamanu oil", "Sea buckthorn"],
    benefits: ["Deeply moisturizes and softens", "Improves fine lines and uneven tone", "Supports brighter complexion", "Enhances overall glow"],
    rating: 5.0, reviews: 15,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_d2571701-17c7-4b3f-add2-7f785eeb8433.jpg",
    badge: "Luxe",
  },
  {
    id: 13, name: "Minted Vanilla Lip Balm", handle: "vanilla-peppermint-lip-balm",
    price: 6, priceFrom: true,
    category: "lips", skinType: ["dry", "sensitive", "mature", "combination"],
    shortDesc: "Nourishing lip balm with Manuka honey 829 and mint",
    description: "A deeply nourishing lip balm that softens, smooths, and protects dry lips while delivering a refreshing minty finish. Formulated with premium Manuka Honey 829 for enhanced moisture and comfort.",
    ingredients: ["Grass-fed tallow", "Beeswax", "Manuka honey 829", "Vitamin E", "Peppermint"],
    benefits: ["Relieves dry, chapped lips", "Locks in long-lasting moisture", "Cooling, refreshing sensation", "Supports healthy lip barrier"],
    rating: 4.9, reviews: 102,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_4e093bc6-131a-44d3-acec-f0685157807e.png",
    badge: "Top Rated",
  },
  {
    id: 14, name: "Orange Blossom & Turmeric Face Cream", handle: "orange-blossom-turmeric-face-cream",
    price: 20,
    category: "body", skinType: ["dry", "mature", "combination", "sensitive"],
    shortDesc: "Brightening body butter with turmeric and orange blossom",
    description: "A rich, full-body moisturizer designed to deeply nourish the skin while enhancing a soft, radiant glow from head to toe.",
    ingredients: ["Vanilla-infused tallow", "Turmeric", "Sweet orange", "Jasmine"],
    benefits: ["Deep, long-lasting hydration", "Promotes smooth, touchable skin", "Enhances natural glow", "Improves appearance of uneven tone"],
    rating: 4.8, reviews: 38,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_69b25102-4c21-42f2-bbb3-316c29552328.png",
  },
  {
    id: 15, name: "Sun Veil", handle: "tantalizingtallow-sun-veil",
    price: 15,
    category: "sun", skinType: ["dry", "sensitive", "mature", "combination"],
    shortDesc: "Natural tallow sun protection",
    description: "A rich, whipped botanical balm designed to nourish and soften the skin while creating a breathable, mineral-based layer for daily outdoor wear. Leaves skin smooth, dewy, and lightly scented with a warm tropical finish.",
    ingredients: ["Beef tallow", "Zinc oxide (non-nano)", "Rosehip oil", "Argan oil", "Beeswax"],
    benefits: ["Deeply moisturizes sun-exposed skin", "Creates protective breathable layer", "Supports smooth radiant glow", "Reduces dryness after time outdoors"],
    rating: 4.6, reviews: 29,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_f4670cee-37e0-4f1d-907b-eeac274e66ed.png",
  },
  {
    id: 16, name: "Vanilla Espresso Coffee Sugar Scrub", handle: "espresso-face-body-scrub",
    price: 12,
    category: "body", skinType: ["dry", "combination", "normal", "mature"],
    shortDesc: "Rich coffee scrub for smooth, nourished skin",
    description: "A rich, whipped coffee scrub that gently exfoliates while leaving skin soft, smooth, and deeply nourished. Designed to elevate your shower into a warm, spa-like ritual.",
    ingredients: ["Coffee (espresso)", "Brown sugar", "Grass-fed tallow", "Castor oil"],
    benefits: ["Smooths rough, dry skin instantly", "Gently exfoliates without stripping", "Improves dull, uneven texture", "Creates warm spa-like experience"],
    rating: 4.8, reviews: 44,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_e7f4990c-f46d-4616-993a-a8b2bd124122.jpg",
  },
  {
    id: 17, name: "Vanilla Sugar Creme", handle: "body-butter-fragrance-of-the-month",
    price: 20, priceFrom: true,
    category: "body", skinType: ["all", "dry"],
    shortDesc: "Sweet, indulgent tallow body cream",
    description: "Dessert for your skin. A rich, whipped body cream that smells like vanilla cupcakes and leaves your skin impossibly soft. The guilt-free indulgence your skin routine has been missing.",
    ingredients: ["Grass-fed tallow", "Vanilla extract", "Raw sugar extract", "Shea butter", "Cocoa butter"],
    benefits: ["Incredibly soft skin", "Intoxicating scent", "Rich hydration", "Mood-boosting"],
    rating: 4.9, reviews: 58,
    image: "https://tantalizingtallow.com/cdn/shop/files/preview_images/a19dae3a897e45e89eccbd290fc71cd3.thumbnail.0000000000.jpg",
  },
  {
    id: 18, name: "Rugged Revival — Men's Collection", handle: "mens-face-cream",
    price: 10, priceFrom: true,
    category: "mens", skinType: ["dry", "mature", "combination", "sensitive"],
    shortDesc: "Men's skincare collection",
    description: "A rich, masculine face cream designed to deeply nourish and smooth the skin while leaving a subtle, cologne-inspired scent. Ideal for restoring softness and supporting a healthy, well-groomed appearance.",
    ingredients: ["Vanilla-infused tallow", "Manuka honey 829", "Castor oil"],
    benefits: ["Deeply hydrates rough dry skin", "Improves fine lines and tired skin", "Supports healthier skin barrier", "Subtle clean masculine scent"],
    rating: 4.7, reviews: 31,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_95b598b9-43a8-4018-81ca-18d3e3a47ecd.jpg",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All Products" },
  { id: "face", label: "Face Creams" },
  { id: "body", label: "Body Butters" },
  { id: "cleanser", label: "Cleansers" },
  { id: "serum", label: "Serums" },
  { id: "hair", label: "Hair Care" },
  { id: "lips", label: "Lip Care" },
  { id: "sun", label: "Sun Care" },
  { id: "mens", label: "Men's" },
];

// Placeholder images (Unsplash) — swap with your Shopify CDN URLs
export const PLACEHOLDER_IMAGES = {
  "blue-tansy": "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&h=600&fit=crop",
  "clarifying-face-cream": "https://images.unsplash.com/photo-1570194065650-d99fb4ee7d5a?w=600&h=600&fit=crop",
  "cleansing-balm": "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop",
  "vanilla-body-butter": "https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=600&h=600&fit=crop",
  "custom-body-butter": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
  "frankincense-manuka": "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop",
  "frankincense-vanilla": "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&h=600&fit=crop",
  "frosted-mint-shimmer": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop",
  "hair-scalp-oil": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&h=600&fit=crop",
  "hyaluronic-serum": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop",
  "magnesium-sleep-balm": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&h=600&fit=crop",
  "luxe-face-cream": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop",
  "lip-balm": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&h=600&fit=crop",
  "orange-blossom-turmeric": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop",
  "sun-veil": "https://images.unsplash.com/photo-1532947974-2e3969737c32?w=600&h=600&fit=crop",
  "coffee-sugar-scrub": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=600&fit=crop",
  "vanilla-sugar-creme": "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=600&h=600&fit=crop",
  "rugged-revival": "https://images.unsplash.com/photo-1581182800629-7d90925ad072?w=600&h=600&fit=crop",
};

// Helper: get image for a product (local file first, then placeholder)
export function getProductImage(product) {
  // If the product has an absolute URL already, use it
  if (product.image && product.image.startsWith("http")) return product.image;
  // Otherwise fall back to placeholder
  return PLACEHOLDER_IMAGES[product.handle] || product.image;
}
