// ─── Brand Constants ───
export const BRAND = {
  name: "Tantalizing Tallow",
  tagline: "Skincare should be simple, sensual, and wildly effective — just like nature intended.",
  freeShipMin: 75,
  colors: {
    bg: "#0a0a0a",
    surface: "#141414",
    card: "#1a1a1a",
    gold: "#c9a84c",
    goldLight: "#e2c97e",
    goldDark: "#a68935",
    text: "#f5f0e8",
    textMuted: "#a09880",
    accent: "#2a2418",
    border: "#2a2520",
  },
};

// ─── Product Database ───
// These are populated from your Shopify store via the Storefront API.
// The static data below serves as the fallback / offline mode so the
// site always renders even without an API connection.
export const PRODUCTS = [
  {
    id: 1, name: "Blue Tansy", handle: "blue-tansy-whipped-face-cream",
    price: 20, priceFrom: true,
    category: "face", skinType: ["sensitive", "acne-prone", "reactive"],
    shortDesc: "Calming, skin-balancing tallow cream with blue tansy",
    description: "A calming, skin-balancing collection made with slowly rendered, triple-filtered tallow and blue tansy to support sensitive, reactive, and acne-prone skin. Blue tansy's azulene content soothes inflammation while tallow delivers deep, biocompatible moisture.",
    ingredients: ["Grass-fed tallow", "Blue tansy essential oil", "Jojoba oil", "Vitamin E"],
    benefits: ["Reduces redness & inflammation", "Balances oil production", "Deeply moisturizes", "Calms reactive skin"],
    rating: 4.9, reviews: 47,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_e92dfc5c-6957-496d-bc61-457818162326.png",
    badge: "Bestseller",
  },
  {
    id: 2, name: "Clarifying Face Cream", handle: "acne-face-cream",
    price: 20,
    category: "face", skinType: ["acne-prone", "oily", "combination"],
    shortDesc: "Tallow face cream for acne-prone skin",
    description: "A lightweight, non-comedogenic tallow face cream specifically formulated for acne-prone skin. Balances sebum production while providing essential fatty acids your skin craves without clogging pores.",
    ingredients: ["Grass-fed tallow", "Tea tree oil", "Niacinamide", "Green tea extract"],
    benefits: ["Clears blemishes", "Balances sebum", "Non-comedogenic", "Antibacterial"],
    rating: 4.8, reviews: 32,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_b69b58da-634f-42a6-9315-a3074867cc93.jpg",
  },
  {
    id: 3, name: "Cleansing Balm", handle: "whipped-tallow-cleansing-balm",
    price: 12,
    category: "cleanser", skinType: ["all"],
    shortDesc: "Gentle tallow-based cleansing balm",
    description: "Melt away makeup, sunscreen, and daily grime with this luxurious tallow cleansing balm. Dissolves impurities without stripping your skin's natural moisture barrier.",
    ingredients: ["Grass-fed tallow", "Castor oil", "Sweet almond oil", "Lavender"],
    benefits: ["Removes makeup gently", "Preserves moisture barrier", "Double-cleanse ready", "Softens skin"],
    rating: 4.7, reviews: 28,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_3a7c3046-cb14-42cc-9a23-f7390a50d103.png",
  },
  {
    id: 4, name: "Vanilla Tallow Body Butter", handle: "cost-effective-vanilla-tallow-body-butter-face-cream",
    price: 6, priceFrom: true,
    category: "body", skinType: ["all", "dry"],
    shortDesc: "Cost-effective vanilla tallow body butter & face cream",
    description: "Rich, whipped tallow body butter with warm vanilla. Our most accessible formula — same premium grass-fed tallow at a price everyone can enjoy. Perfect for daily full-body moisture.",
    ingredients: ["Grass-fed tallow", "Vanilla extract", "Coconut oil", "Shea butter"],
    benefits: ["Deep hydration", "Warm vanilla scent", "Budget-friendly", "Full body use"],
    rating: 4.9, reviews: 89,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_8552804f-9d37-49aa-bbaa-309c203b10d5.png",
    badge: "Best Value",
  },
  {
    id: 5, name: "Custom Whipped Body Butter", handle: "vanilla-velvet-body-butter",
    price: 20,
    category: "body", skinType: ["all"],
    shortDesc: "Pure, essential oil, or fragrance options",
    description: "Your tallow, your way. Choose pure unscented, essential oil blends, or fragrance options. Each jar is hand-whipped to a cloud-like consistency from triple-filtered grass-fed tallow.",
    ingredients: ["Grass-fed tallow", "Your choice of scent", "Jojoba oil"],
    benefits: ["Customizable scent", "Hand-whipped texture", "Ultra-moisturizing", "Clean ingredients"],
    rating: 4.8, reviews: 56,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_cece441f-aec1-4fdd-bf1e-5a2f3ac7b3af.png",
  },
  {
    id: 6, name: "Frankincense & Manuka Honey Face Cream", handle: "frankincense-manuka-honey-face-cream",
    price: 40,
    category: "face", skinType: ["mature", "dry", "damaged"],
    shortDesc: "Premium face cream with 1122+ MGO Manuka honey",
    description: "Our most luxurious face cream. Frankincense promotes cellular renewal while 1122+ MGO Manuka honey delivers unmatched antibacterial and healing properties. For skin that demands the best.",
    ingredients: ["Grass-fed tallow", "Frankincense essential oil", "Manuka honey 1122+ MGO", "Rosehip oil"],
    benefits: ["Cellular renewal", "Antibacterial healing", "Deep anti-aging", "Intense repair"],
    rating: 5.0, reviews: 23,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_29113693-29da-4026-8e80-da9c0f5f5ea3.png",
    badge: "Premium",
  },
  {
    id: 7, name: "Frankincense & Vanilla Face Cream", handle: "vanilla-frankincense-face-cream",
    price: 22,
    category: "face", skinType: ["mature", "normal", "dry"],
    shortDesc: "Anti-aging tallow face cream",
    description: "The anti-aging powerhouse. Frankincense stimulates collagen while vanilla soothes and comforts. A daily ritual for skin that's aging gracefully with nature's most time-tested ingredients.",
    ingredients: ["Grass-fed tallow", "Frankincense essential oil", "Vanilla extract", "Vitamin E"],
    benefits: ["Stimulates collagen", "Reduces fine lines", "Deeply nourishing", "Warm, comforting scent"],
    rating: 4.8, reviews: 41,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_e3c864e2-f288-4ab6-b18f-fe62e38199e0.png",
  },
  {
    id: 8, name: "Frosted Mint Shimmer Body Butter", handle: "summer-shimmer-body-butter",
    price: 16,
    category: "body", skinType: ["all"],
    shortDesc: "Whipped tallow body butter with shimmer",
    description: "A playful twist on our classic body butter. Cooling mint meets a subtle shimmer for skin that glows. Perfect for summer evenings or anytime you want that extra radiance.",
    ingredients: ["Grass-fed tallow", "Peppermint oil", "Mica shimmer", "Coconut oil"],
    benefits: ["Cooling sensation", "Subtle shimmer glow", "Deep moisture", "Fun & playful"],
    rating: 4.7, reviews: 19,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_1a58a8db-7e15-4eea-84c1-c8752e5a0e0a.png",
  },
  {
    id: 9, name: "Hair & Scalp Oil", handle: "nourish-restore-hair-oil",
    price: 18,
    category: "hair", skinType: ["all"],
    shortDesc: "Tallow growth oil for thicker, shinier hair",
    description: "Nourish from root to tip. This tallow-based hair oil penetrates the scalp to promote growth while taming frizz and adding brilliant shine. Lightweight enough for daily use.",
    ingredients: ["Grass-fed tallow", "Rosemary oil", "Castor oil", "Argan oil", "Biotin"],
    benefits: ["Promotes hair growth", "Reduces frizz", "Adds shine", "Strengthens follicles"],
    rating: 4.6, reviews: 34,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_77a7760d-54db-40a3-a878-2d94a2c60fbb.jpg?v=1747893332",
  },
  {
    id: 10, name: "Hyaluronic Acid Serum", handle: "hydrabloom-botanical-serum",
    price: 12,
    category: "serum", skinType: ["all", "dehydrated"],
    shortDesc: "Hydrating serum for all skin types",
    description: "Layer this lightweight hyaluronic acid serum under your tallow cream for maximum hydration. Draws moisture into the skin and locks it in. The perfect companion to any tallow moisturizer.",
    ingredients: ["Hyaluronic acid", "Aloe vera", "Glycerin", "Rose water"],
    benefits: ["Intense hydration", "Plumps fine lines", "Lightweight layering", "All skin types"],
    rating: 4.7, reviews: 22,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_1b821661-94b3-4183-be44-ff92af969fcd.png",
  },
  {
    id: 11, name: "Lavender & Vanilla Magnesium Sleep Balm", handle: "lavender-and-magnesium-calming-cream",
    price: 18, priceFrom: true,
    category: "body", skinType: ["all"],
    shortDesc: "Relaxing magnesium balm for better sleep",
    description: "Wind down naturally. Magnesium absorbs through the skin to relax muscles and calm the mind, while lavender and vanilla create the ultimate bedtime ritual. Apply to feet, wrists, or temples.",
    ingredients: ["Grass-fed tallow", "Magnesium chloride", "Lavender essential oil", "Vanilla"],
    benefits: ["Promotes deeper sleep", "Relaxes muscles", "Calms anxiety", "Bedtime ritual"],
    rating: 4.9, reviews: 67,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_8ab265f4-f5ed-42aa-a91a-0b83eb1837a7.png",
    badge: "Fan Favorite",
  },
  {
    id: 12, name: "Luxe Face Cream", handle: "luxe-face-cream",
    price: 60,
    category: "face", skinType: ["mature", "dry", "normal"],
    shortDesc: "Ultra-premium tallow face cream",
    description: "The crown jewel. Every ingredient is the finest available — from our slowest-rendered tallow to rare botanical extracts. For those who accept nothing but the absolute best for their skin.",
    ingredients: ["Triple-filtered grass-fed tallow", "Bakuchiol", "Squalane", "Frankincense", "Rose otto", "24K gold flakes"],
    benefits: ["Ultimate luxury", "Visible anti-aging", "Radiant glow", "Rare ingredients"],
    rating: 5.0, reviews: 15,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_d2571701-17c7-4b3f-add2-7f785eeb8433.jpg",
    badge: "Luxe",
  },
  {
    id: 13, name: "Minted Vanilla Lip Balm", handle: "vanilla-peppermint-lip-balm",
    price: 6, priceFrom: true,
    category: "lips", skinType: ["all"],
    shortDesc: "Tallow + Manuka honey lip balm",
    description: "Heal and protect your lips with tallow and Manuka honey. A hint of mint tingles while vanilla sweetens. Never waxy, always buttery smooth. You'll never go back to drugstore balm.",
    ingredients: ["Grass-fed tallow", "Manuka honey", "Peppermint oil", "Vanilla", "Beeswax"],
    benefits: ["Heals cracked lips", "Long-lasting moisture", "Never waxy", "Manuka healing"],
    rating: 4.9, reviews: 102,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_4e093bc6-131a-44d3-acec-f0685157807e.png",
    badge: "Top Rated",
  },
  {
    id: 14, name: "Orange Blossom & Turmeric Face Cream", handle: "orange-blossom-turmeric-face-cream",
    price: 20,
    category: "face", skinType: ["dull", "uneven", "hyperpigmentation"],
    shortDesc: "Brightening tallow face cream",
    description: "Brighten and even your complexion naturally. Turmeric's curcumin fades dark spots while orange blossom revitalizes dull skin. A radiance-boosting daily cream for your most luminous skin.",
    ingredients: ["Grass-fed tallow", "Turmeric extract", "Orange blossom water", "Vitamin C"],
    benefits: ["Brightens complexion", "Fades dark spots", "Anti-inflammatory", "Evens skin tone"],
    rating: 4.8, reviews: 38,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_69b25102-4c21-42f2-bbb3-316c29552328.png",
  },
  {
    id: 15, name: "Sun Veil", handle: "tantalizingtallow-sun-veil",
    price: 15,
    category: "sun", skinType: ["all"],
    shortDesc: "Natural tallow sun protection",
    description: "Lightweight, mineral-based sun protection in a tallow base. Shields without the white cast or chemical filters. Your skin stays protected, moisturized, and free from synthetic sunscreen ingredients.",
    ingredients: ["Grass-fed tallow", "Non-nano zinc oxide", "Raspberry seed oil", "Carrot seed oil"],
    benefits: ["Mineral sun protection", "No white cast", "Moisturizes while protecting", "Chemical-free"],
    rating: 4.6, reviews: 29,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_f4670cee-37e0-4f1d-907b-eeac274e66ed.png",
  },
  {
    id: 16, name: "Vanilla Espresso Coffee Sugar Scrub", handle: "espresso-face-body-scrub",
    price: 12,
    category: "body", skinType: ["all"],
    shortDesc: "Exfoliating coffee scrub",
    description: "Wake up your skin. Coffee grounds exfoliate while caffeine boosts circulation and reduces puffiness. Vanilla and espresso create an intoxicating scent that turns your shower into a spa.",
    ingredients: ["Raw sugar", "Coffee grounds", "Grass-fed tallow", "Vanilla extract", "Coconut oil"],
    benefits: ["Exfoliates dead skin", "Boosts circulation", "Reduces puffiness", "Spa-like experience"],
    rating: 4.8, reviews: 44,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_e7f4990c-f46d-4616-993a-a8b2bd124122.jpg",
  },
  {
    id: 17, name: "Vanilla Sugar Creme", handle: "body-butter-fragrance-of-the-month",
    price: 20, priceFrom: true,
    category: "body", skinType: ["all", "dry"],
    shortDesc: "Sweet, indulgent tallow body cream",
    description: "Dessert for your skin. A rich, whipped body cream that smells like vanilla cupcakes and leaves your skin impossibly soft. The guilt-free indulgence your skin routine has been missing.",
    ingredients: ["Grass-fed tallow", "Vanilla extract", "Raw sugar extract", "Shea butter", "Cocoa butter"],
    benefits: ["Incredibly soft skin", "Intoxicating scent", "Rich hydration", "Mood-boosting"],
    rating: 4.9, reviews: 58,
    image: "https://tantalizingtallow.com/cdn/shop/files/preview_images/a19dae3a897e45e89eccbd290fc71cd3.thumbnail.0000000000.jpg",
  },
  {
    id: 18, name: "Rugged Revival — Men's Collection", handle: "mens-face-cream",
    price: 10, priceFrom: true,
    category: "mens", skinType: ["all"],
    shortDesc: "Men's skincare collection",
    description: "Skincare isn't just for her. Rugged Revival is tallow skincare built for men — no frills, no floral, just effective. Cedarwood, sandalwood, and black pepper in a no-nonsense formulation.",
    ingredients: ["Grass-fed tallow", "Cedarwood oil", "Sandalwood", "Black pepper oil", "Charcoal"],
    benefits: ["Masculine scent profile", "Post-shave healing", "Deep moisture", "No-nonsense routine"],
    rating: 4.7, reviews: 31,
    image: "https://tantalizingtallow.com/cdn/shop/files/rn-image_picker_lib_temp_95b598b9-43a8-4018-81ca-18d3e3a47ecd.jpg",
  },
];

export const CATEGORIES = [
  { id: "all", label: "All Products" },
  { id: "face", label: "Face Creams" },
  { id: "body", label: "Body Butters" },
  { id: "cleanser", label: "Cleansers" },
  { id: "serum", label: "Serums" },
  { id: "hair", label: "Hair Care" },
  { id: "lips", label: "Lip Care" },
  { id: "sun", label: "Sun Care" },
  { id: "mens", label: "Men's" },
];

// Placeholder images (Unsplash) — swap with your Shopify CDN URLs
export const PLACEHOLDER_IMAGES = {
  "blue-tansy": "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&h=600&fit=crop",
  "clarifying-face-cream": "https://images.unsplash.com/photo-1570194065650-d99fb4ee7d5a?w=600&h=600&fit=crop",
  "cleansing-balm": "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop",
  "vanilla-body-butter": "https://images.unsplash.com/photo-1601049676869-702ea24cfd58?w=600&h=600&fit=crop",
  "custom-body-butter": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=600&fit=crop",
  "frankincense-manuka": "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&h=600&fit=crop",
  "frankincense-vanilla": "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=600&h=600&fit=crop",
  "frosted-mint-shimmer": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop",
  "hair-scalp-oil": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=600&h=600&fit=crop",
  "hyaluronic-serum": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop",
  "magnesium-sleep-balm": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=600&h=600&fit=crop",
  "luxe-face-cream": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=600&fit=crop",
  "lip-balm": "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&h=600&fit=crop",
  "orange-blossom-turmeric": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&h=600&fit=crop",
  "sun-veil": "https://images.unsplash.com/photo-1532947974-2e3969737c32?w=600&h=600&fit=crop",
  "coffee-sugar-scrub": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=600&fit=crop",
  "vanilla-sugar-creme": "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=600&h=600&fit=crop",
  "rugged-revival": "https://images.unsplash.com/photo-1581182800629-7d90925ad072?w=600&h=600&fit=crop",
};

// Helper: get image for a product (local file first, then placeholder)
export function getProductImage(product) {
  // If the product has an absolute URL already, use it
  if (product.image && product.image.startsWith("http")) return product.image;
  // Otherwise fall back to placeholder
  return PLACEHOLDER_IMAGES[product.handle] || product.image;
}
